[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "gitsentinel"
version = "0.1.0"
dependencies = [
	"typer>=0.9.0",
	"anthropic>=0.40.0",
	"python-dotenv>=1.0.0",
]

[project.scripts]
gs = "gitsentinel.cli:main"

[tools.setuptools.packages.find]
where = ["src"]